modLoader = "javafml"
loaderVersion = "*"
license = "All rights reserved"
issueTrackerURL = "https://github.com/henkelmax/pipez/issues"
[[mods]]
modId = "pipez"
version = "${mod_version}"
displayName = "Pipez"
updateJSONURL = "https://update.maxhenkel.de/forge/pipez"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/pipez"
logoFile = "icon.png"
authors = "Max Henkel"
description = '''Simple and efficient pipes'''
[[dependencies.pipez]]
modId = "forge"
mandatory = true
versionRange = "${forge_dependency}"
ordering = "NONE"
side = "BOTH"
[[dependencies.pipez]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version}]"
ordering = "NONE"
side = "BOTH"
[[dependencies.pipez]]
modId = "mekanism"
mandatory = false
versionRange = "${mekanism_dependency}"
ordering = "AFTER"
side = "BOTH"
[[dependencies.pipez]]
modId = "jei"
mandatory = false
versionRange = "*"
ordering = "NONE"
side = "BOTH"
[[dependencies.pipez]]
modId = "theoneprobe"
mandatory = false
versionRange = "*"
ordering = "NONE"
side = "BOTH"
[[dependencies.pipez]]
modId = "jade"
mandatory = false
versionRange = "*"
ordering = "NONE"
side = "BOTH"